model:
  patch_size: 16
  tubelet_size: 1
  embed_dim: 768
  spatial_num_heads: 12
  spatial_num_layers: 12
  temporal_num_heads: 12
  temporal_num_layers: 12
  num_classes: 10
  max_seq_length: 16
  image_size: 224
  use_vit: True  # To use ViT encoder with Conv2d instead of tubelet with Conv3d

data:
  batch_size: 2
  min_sequence_length: 2
  max_sequence_length: 16
  frame_sample_rate: 1
  num_channels: 3
  height: 224
  width: 224
  meta_file: /media/zeleznyt/DATA/data/RAVDAI/annotations.json
  shuffle: True
  drop_last: True
  num_workers: 0 # Higher number not supported yet because of PyAV
  video_decoder: decord

training:
  learning_rate: 0.0001
  epochs: 50
  log_step: 50
  eval_step: 50
  save_step: 50
  checkpoint_save_dir: /media/zeleznyt/DATA/repo/ViViT/checkpoints
#  weight_decay: 0.0001
#  optimizer: "adam"